#spring.application.name=chat
#
#server.port=${PORT}
#
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.open-in-view=false
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
#chat.app.jwtSecret=${JWT_SECRET}
#chat.app.jwtExpirationMs=3600000
#chat.app.jwtRefreshExpirationMs=604800000
#
#chat.upload.dir=${UPLOAD_DIR}
#spring.servlet.multipart.max-file-size=10MB
#spring.servlet.multipart.max-request-size=10MB
#
##app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
#
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=${MAIL_USERNAME}
#spring.mail.password=${MAIL_PASSWORD}
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#app.mail.from=${MAIL_FROM:${MAIL_USERNAME}}

spring.application.name=chat

spring.datasource.url=jdbc:postgresql://localhost:5432/chat
spring.datasource.username=postgres
spring.datasource.password=nita123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

chat.app.jwtSecret=45NbTmtErOz8EgXVZka6cFJW1MTF/SNinoyyu7cUQuI=
chat.app.jwtExpirationMs=3600000
chat.app.jwtRefreshExpirationMs=604800000

chat.upload.dir=./uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=n79624514@gmail.com
spring.mail.password=bvkvprdugyqmtofx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
app.mail.from=${MAIL_FROM:${spring.mail.username}}
app.cors.allowed-origins=http://localhost:3000,http://localhost:5173,https://nita-chat-ui.vercel.app